<?php include 'header.phtml'; ?>

<main id="biography" class="container">
	<img src="images/jim-bio.jpg">

	<h1>Humana Project</h1>

	<div id="text">
		<p>Humana Project voit le jour à Nantes en 2018.
		Une initiative simple : entreprendre et bâtir un projet artistique gravitant autour de la musique, pour y faire parvenir une note de poésie et d’engagement militant.
		Incarnant un personnage à l’allure d’écrivain intemporel, il ajoute une touche de mystère et de fantaisie à son univers nuancé.
		</p>
		<p>La musique électronique souvent ressentie de façon personnelle se voit guidé par un fil conducteur, une histoire, qui prend racine dans des valeurs humanistes et élémentaires.</p>
		<p>Au travers de ce mode de communication il puise ses influences aussi bien en musique classique et traditionnelle, qu’en musique électronique en tout genre. 
		Il s’épanouit dans la musique techno mais n’hésite pas à étendre ses frontières créatives pour donner naissance à de nouvelles réalisations.</p>
	</div>

      
</main>