<?php include 'header.phtml'; ?>

<main class="img2 container" id="discography">
	<div class="flex">
			<div>
				<h1>Singles</h1>
				<p><small>2017</small> <strong>Swiftness</strong></p>
				<p><small>2017</small> <strong>Earth Moaning</strong></p>
				<p><small>2017</small> <strong>Panthera</strong></p>
				<p><small>2017</small> <strong>L'oiseau d'argent</strong></p>
				<p><small>2017</small> <strong>Glitch Forest</strong></p>
				<p><small>2017</small> <strong>Shaya</strong></p>
				<p><small>2017</small> <strong>Valse nocturne</strong></p>
				<p><small>2017</small> <strong>Kundalini</strong></p>
				<p><small>2017</small> <strong>Le Mat</strong></p>
			</div>
			<div>
				<h1>Albums</h1>
				<p><small>2018</small> <strong>Tome 1 - Entre rêve et matière</strong> </p>
				<br>
				<br>
				<h1>Remix</h1>
				<p><small>2018 </small><strong>Sub Family Jam - Smoked Stoep( Humana Project remix )</strong></p>
			</div>
	</div>
			<div class="clear"></div>
</main>