<?php include 'header.phtml'; ?>

<main class="container">
	<h1>Photos</h1>
		<div class="gallery">
			<a href="../public/images/pic1.jpg" data-lightbox="mygallery"><img class="grow" src="images/pic1_small.jpg"></a>

		    <a href="../public/images/pic2.jpg" data-lightbox="mygallery"><img class="grow" src="images/pic2_small.jpg"></a>

		    <a href="../public/images/pic3.jpg" data-lightbox="mygallery"><img class="grow" src="images/pic3.jpg"></a>

		    <a href="../public/images/pic4.jpg" data-lightbox="mygallery"><img class="grow" src="images/pic4_small.jpg"></a>

		    <a href="../public/images/pic5.jpg" data-lightbox="mygallery"><img class="grow" src="images/pic5_small.jpg"></a>

		    <a href="../public/images/pic6.jpg" data-lightbox="mygallery"><img class="grow" src="images/pic6_small.jpg"></a>
		</div>
			

	<h1 style="margin-top: 100px">Videos</h1>
		<div id="video">
			<iframe width="560" height="315" src="https://www.youtube.com/embed/n8gZ_A5ptJM" frameborder="0" allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>

			<iframe width="560" height="315" src="https://www.youtube.com/embed/C2EOxHLnEoY" frameborder="0" allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>
		</div>




	</main>
	<script type="text/javascript" src="js/lightbox-plus-jquery.min.js"></script>